[General]

Background="Ryo.jpg"
DimBackgroundImage="0.1"
## Leggermente scurito per far risaltare gli elementi chiari

ScaleImageCropped="true"
ScreenWidth=2208
ScreenHeight=1242

## [Blur Settings]

FullBlur="false"
PartialBlur="true"
BlurRadius="100"

## [Design Customizations]

HaveFormBackground="false"
FormPosition="left"
BackgroundImageHAlignment="center"
BackgroundImageVAlignment="center"

MainColor="#b0e2ff"
## Un azzurro ghiaccio chiaro per i testi e le icone non attive. Molto leggibile su blu scuro.

AccentColor="#00fbff"
## Ciano elettrico per il focus e l'orologio. Crea il distacco necessario restando nella scala dei blu.

BackgroundColor="rgba(0, 30, 60, 0.5)"
## Un blu notte semitrasparente per i menu a tendina, così si fonde con lo sfondo.

OverrideLoginButtonTextColor="#ffffff"
## Bianco puro per il testo del pulsante per la massima chiarezza.

InterfaceShadowSize="6"
InterfaceShadowOpacity="0.4"
RoundCorners="20"
ScreenPadding="0"
Font="Noto Sans"
FontSize=""

## [Interface Behavior]

ForceRightToLeft="false"
ForceLastUser="true"
ForcePasswordFocus="true"
ForceHideCompletePassword="true"
ForceHideVirtualKeyboardButton="false"
ForceHideSystemButtons="false"
AllowEmptyPassword="true"
AllowBadUsernames="true"

## [Locale Settings]

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d of MMMM"

## [Translations]

HeaderText="Welcome, Sensei"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateShowPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSession=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateVirtualKeyboardButton=""

#NOTE Made with Machillka
ButtonColor="rgba(70, 162, 218, 0.6)"
## Blu Arona semitrasparente per i tasti.

ButtonTextColor="#ffffff"
FontSizeScale="1.2"
