# Generated by kara install.sh
export PATH="$HOME/.local/bin:$PATH"
export XDG_DATA_DIRS="$HOME/.local/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export XDG_CONFIG_DIRS="$HOME/.local/etc/xdg:${XDG_CONFIG_DIRS:-/etc/xdg}"
export QML2_IMPORT_PATH="$HOME/.local/lib/qml:${QML2_IMPORT_PATH}"
export QT_PLUGIN_PATH="$HOME/.local/lib/plugins:${QT_PLUGIN_PATH}"
